services:
  mkdocs:
    build: .
    hostname: mkdocs
    # use build to build everything locally which then can be pushed to server
    # command: "build"
    command: "serve --dev-addr=0.0.0.0:8000"
    volumes:
      - .:/docs
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true
