site_name: David Gunnarsson | A Personal Blog
site_url: https://davegson.com
theme:
  name: material
  logo: /assets/img/davegson.jpg
  favicon: /assets/img/davegson.jpg
  font:
    text: Lato
  icon:
    repo: fontawesome/brands/github
  custom_dir: overrides
  features:
    # - navigation.instant # this messed up the live verion for David with Brave, remove to quickfix, maybe reconsider in the future
    - navigation.top
    - navigation.tracking
    - navigation.sections

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra_css:
  - assets/css/reset.css
  - assets/css/tooltips.css
  - assets/css/global.css
  - assets/css/nav.css
  - assets/css/footer.css
  - assets/css/tweaks.css
  - assets/css/cv.css
  - assets/css/blog.css

plugins:
  - search
  - privacy
  - blog:
      pagination_per_page: 5
      blog_dir: .
      categories_allowed:
        - A Builder's Journey
        - Coding
        - Marketing
        - Philosophy
        - Writing
  - rss:
      match_path: blog/posts/.*
      date_from_meta:
        as_creation: date
      categories:
        - categories
        - tags